interface ZIF_CDS_LMO_013_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCDS_LMO_013,
 CREATE_ZCDS_LMO_013            TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03EEC05',
 DELETE_ZCDS_LMO_013            TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03F6C05',
 LOCK_ZCDS_LMO_013              TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03E2C05',
 SAVE_ZCDS_LMO_013              TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03FEC05',
 UNLOCK_ZCDS_LMO_013            TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03E6C05',
 UPDATE_ZCDS_LMO_013            TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03F2C05',
 VALIDATE_ZCDS_LMO_013          TYPE /BOBF/ACT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03FAC05',
      END OF ZCDS_LMO_013,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCDS_LMO_013,
        BEGIN OF LOCK_ZCDS_LMO_013,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZCDS_LMO_013,
        BEGIN OF UNLOCK_ZCDS_LMO_013,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZCDS_LMO_013,
      END OF ZCDS_LMO_013,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCDS_LMO_013,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'F15762B62FC51EEEBDEF35EBD040CC05',
      END OF ZCDS_LMO_013,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCDS_LMO_013,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03E0C05',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03DCC05',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03ECC05',
      END OF ZCDS_LMO_013,
      BEGIN OF ZCDS_LMO_013_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'F15762B62FC51EEEBDEF35EBD0404C05',
      END OF ZCDS_LMO_013_LOCK,
      BEGIN OF ZCDS_LMO_013_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'F15762B62FC51EEEBDEF35EBD0402C05',
      END OF ZCDS_LMO_013_MESSAGE,
      BEGIN OF ZCDS_LMO_013_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'F15762B62FC51EEEBDEF35EBD0406C05',
      END OF ZCDS_LMO_013_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCDS_LMO_013,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCDS_LMO_013,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03D0C05' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCDS_LMO_013' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCDS_LMO_013,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE 'F15762B62FC51EEEBDEF35EBD040EC05',
      END OF ZCDS_LMO_013,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZCDS_LMO_013                   TYPE /BOBF/OBM_GROUP_KEY VALUE 'F15762B62FC51EEEBDEF35EBD046AC05',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCDS_LMO_013                   TYPE /BOBF/OBM_NODE_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03D6C05',
 ZCDS_LMO_013_LOCK              TYPE /BOBF/OBM_NODE_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03DEC05',
 ZCDS_LMO_013_MESSAGE           TYPE /BOBF/OBM_NODE_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03DAC05',
 ZCDS_LMO_013_PROPERTY          TYPE /BOBF/OBM_NODE_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03EAC05',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCDS_LMO_013,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  USERID                         TYPE STRING VALUE 'USERID',
  EMAIL                          TYPE STRING VALUE 'EMAIL',
  FULLNAME                       TYPE STRING VALUE 'FULLNAME',
  ISNEW                          TYPE STRING VALUE 'ISNEW',
  LASTCHANGEDAT                  TYPE STRING VALUE 'LASTCHANGEDAT',
  TOOLNAME                       TYPE STRING VALUE 'TOOLNAME',
  KNOWLEDGE                      TYPE STRING VALUE 'KNOWLEDGE',
  INTEREST                       TYPE STRING VALUE 'INTEREST',
  TRAINING                       TYPE STRING VALUE 'TRAINING',
      END OF ZCDS_LMO_013,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCDS_LMO_013,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'F15762B62FC51EEEBDEF35EBD03D8C05',
      END OF ZCDS_LMO_013,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZCDS_LMO_013,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE 'F15762B62FC51EEEBDEF35EBD0412C05',
      END OF ZCDS_LMO_013,
    END OF SC_VALIDATION .
endinterface.
